#!/usr/bin/env python3
"""skill-dashboard.py — 生成 skill 健康度 HTML 仪表盘"""

import json
import os

DATA_DIR = os.path.expanduser("~/.openclaw/workspace/data")
HEALTH_PATH = os.path.join(DATA_DIR, "skill-health.json")
REGISTRY_PATH = os.path.join(DATA_DIR, "skill-registry.json")
OUTPUT_PATH = os.path.join(DATA_DIR, "skill-dashboard.html")

def load_json(path):
    if not os.path.exists(path):
        return {}
    with open(path, 'r') as f:
        return json.load(f)

def main():
    health = load_json(HEALTH_PATH)
    registry_list = load_json(REGISTRY_PATH) if os.path.exists(REGISTRY_PATH) else []
    registry = {s["id"]: s for s in registry_list} if isinstance(registry_list, list) else {}

    rows = []
    for sid, h in sorted(health.items(), key=lambda x: x[1]["score"], reverse=True):
        cat = registry.get(sid, {}).get("category", "—")
        src = registry.get(sid, {}).get("source", "—")
        status_emoji = {"healthy": "🟢", "needs_optimization": "🟡", "critical": "🔴", "unused": "⚪"}.get(h["status"], "❓")
        rows.append(f"""<tr>
  <td>{status_emoji}</td><td>{sid}</td><td>{cat}</td><td>{src}</td>
  <td><div class="bar" style="width:{h['score']}%">{h['score']}</div></td>
  <td>{h['total_uses']}</td><td>{h['success_rate']:.0%}</td><td>{h['accept_rate']:.0%}</td>
</tr>""")

    html = f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Skill Dashboard</title>
<style>
body {{ font-family: -apple-system, sans-serif; margin: 20px; background: #1a1a2e; color: #eee; }}
h1 {{ color: #e94560; }}
table {{ border-collapse: collapse; width: 100%; }}
th, td {{ padding: 8px 12px; text-align: left; border-bottom: 1px solid #333; }}
th {{ background: #16213e; color: #e94560; }}
tr:hover {{ background: #16213e; }}
.bar {{ background: linear-gradient(90deg, #e94560, #0f3460); color: #fff; padding: 2px 8px; border-radius: 4px; font-size: 12px; min-width: 20px; text-align: center; }}
.legend {{ display: flex; gap: 20px; margin: 10px 0; }}
.legend span {{ font-size: 14px; }}
</style></head><body>
<h1>🎯 Skill 健康度仪表盘</h1>
<div class="legend">
  <span>🟢 健康</span><span>🟡 需优化</span><span>🔴 严重</span><span>⚪ 未使用</span>
</div>
<table>
<tr><th></th><th>Skill</th><th>分类</th><th>来源</th><th>健康分</th><th>使用次数</th><th>成功率</th><th>接受率</th></tr>
{"".join(rows)}
</table>
<p style="color:#666;margin-top:20px">Generated by skill-dashboard.py</p>
</body></html>"""

    with open(OUTPUT_PATH, 'w') as f:
        f.write(html)
    print(f"📊 Dashboard: {OUTPUT_PATH}")

if __name__ == "__main__":
    main()
